// export const ADD_TO_CART_PRODUCT = "ADD_TO_CART_PRODUCT";
// export const REMOVE_FROM_CART_PRODUCT = "REMOVE_FROM_CART_PRODUCT";
// export const CLEAR_CART_PRODUCT = "CLEAR_CART_PRODUCT";
// export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
// export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
// export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";